### ISSUE TITLE
What does "escape" do? Shouldn't it be zPow?

### ISSUE THREAD

**Issue by qdm12** [HPCE/hpce-2015-cw6#4]
Hi everyone,

I found out there is a variable real_t escape=2; which is always 2 used in iter for generate_field.
I wonder if this isn't a mistake and if escape should actually be zPow for example. 

Anyone has any idea ?

Thanks !!

**Comment by m8pple** [comment]
Escape and zPow are distinct variables.

Escape defines the escape radius for the orbit associated with a pixel. I happened to
hard-code it to 2 as there is not much visual change as it is varied, but it affects the
image independently of zPow.
